-- Canonical South African university and campus reference data.
-- This migration is idempotent so deployments receive public reference data
-- automatically while preserving stable IDs and any unrelated local rows.
insert into public.universities (name, acronym, slug, notes)
values
  ('Cape Peninsula University of Technology', 'CPUT', 'cape-peninsula-university-of-technology', null),
  ('Central University of Technology', 'CUT', 'central-university-of-technology', null),
  ('Durban University of Technology', 'DUT', 'durban-university-of-technology', null),
  ('Mangosuthu University of Technology', 'MUT', 'mangosuthu-university-of-technology', null),
  ('Nelson Mandela University', 'NMU', 'nelson-mandela-university', null),
  ('North-West University', 'NWU', 'north-west-university', null),
  ('Rhodes University', 'RU', 'rhodes-university', null),
  ('Sefako Makgatho Health Sciences University', 'SMU', 'sefako-makgatho-health-sciences-university', null),
  ('Sol Plaatje University', 'SPU', 'sol-plaatje-university', null),
  ('Stellenbosch University', 'SU', 'stellenbosch-university', null),
  ('Tshwane University of Technology', 'TUT', 'tshwane-university-of-technology', null),
  ('University of Cape Town', 'UCT', 'university-of-cape-town', null),
  ('University of Fort Hare', 'UFH', 'university-of-fort-hare', null),
  ('University of Johannesburg', 'UJ', 'university-of-johannesburg', null),
  ('University of KwaZulu-Natal', 'UKZN', 'university-of-kwazulu-natal', null),
  ('University of Limpopo', 'UL', 'university-of-limpopo', null),
  ('University of Mpumalanga', 'UMP', 'university-of-mpumalanga', null),
  ('University of Pretoria', 'UP', 'university-of-pretoria', null),
  ('University of South Africa', 'UNISA', 'university-of-south-africa', 'UNISA is primarily a distance-learning university with support centres across the country.'),
  ('University of the Free State', 'UFS', 'university-of-the-free-state', null),
  ('University of the Western Cape', 'UWC', 'university-of-the-western-cape', null),
  ('University of the Witwatersrand', 'Wits', 'university-of-the-witwatersrand', null),
  ('University of Venda', 'UNIVEN', 'university-of-venda', null),
  ('University of Zululand', 'UNIZULU', 'university-of-zululand', null),
  ('Walter Sisulu University', 'WSU', 'walter-sisulu-university', null)
on conflict (slug) do update
set
  name = excluded.name,
  acronym = excluded.acronym,
  notes = excluded.notes;

insert into public.campuses (university_id, name, city, province)
select
  universities.id,
  campus_seed.name,
  campus_seed.city,
  campus_seed.province
from (
  values
  ('cape-peninsula-university-of-technology', 'Bellville Campus', 'Cape Town', 'Western Cape'),
  ('cape-peninsula-university-of-technology', 'Cape Town Campus', 'Cape Town', 'Western Cape'),
  ('cape-peninsula-university-of-technology', 'Mowbray Campus', 'Cape Town', 'Western Cape'),
  ('cape-peninsula-university-of-technology', 'Wellington Campus', 'Wellington', 'Western Cape'),
  ('cape-peninsula-university-of-technology', 'Granger Bay Campus', 'Cape Town', 'Western Cape'),
  ('central-university-of-technology', 'Bloemfontein Campus', 'Bloemfontein', 'Free State'),
  ('central-university-of-technology', 'Welkom Campus', 'Welkom', 'Free State'),
  ('durban-university-of-technology', 'Steve Biko Campus', 'Durban', 'KwaZulu-Natal'),
  ('durban-university-of-technology', 'M.L. Sultan Campus', 'Durban', 'KwaZulu-Natal'),
  ('durban-university-of-technology', 'Ritson Campus', 'Durban', 'KwaZulu-Natal'),
  ('durban-university-of-technology', 'Indumiso Campus', 'Pietermaritzburg', 'KwaZulu-Natal'),
  ('durban-university-of-technology', 'Riverside Campus', 'Durban', 'KwaZulu-Natal'),
  ('mangosuthu-university-of-technology', 'Main Campus', 'Umlazi', 'KwaZulu-Natal'),
  ('nelson-mandela-university', 'Missionvale Campus', 'Gqeberha', 'Eastern Cape'),
  ('nelson-mandela-university', 'George Campus', 'George', 'Western Cape'),
  ('nelson-mandela-university', 'North Campus', 'Gqeberha', 'Eastern Cape'),
  ('nelson-mandela-university', 'South Campus', 'Gqeberha', 'Eastern Cape'),
  ('nelson-mandela-university', 'Second Avenue Campus', 'Gqeberha', 'Eastern Cape'),
  ('nelson-mandela-university', 'Bird Street Campus', 'Gqeberha', 'Eastern Cape'),
  ('nelson-mandela-university', 'Ocean Sciences Campus', 'Gqeberha', 'Eastern Cape'),
  ('north-west-university', 'Mahikeng Campus', 'Mahikeng', 'North West'),
  ('north-west-university', 'Potchefstroom Campus', 'Potchefstroom', 'North West'),
  ('north-west-university', 'Vanderbijlpark Campus', 'Vanderbijlpark', 'Gauteng'),
  ('rhodes-university', 'Main Campus', 'Makhanda', 'Eastern Cape'),
  ('sefako-makgatho-health-sciences-university', 'Ga-Rankuwa Campus', 'Pretoria', 'Gauteng'),
  ('sol-plaatje-university', 'Main Campus', 'Kimberley', 'Northern Cape'),
  ('stellenbosch-university', 'Stellenbosch Campus', 'Stellenbosch', 'Western Cape'),
  ('stellenbosch-university', 'Tygerberg Campus', 'Cape Town', 'Western Cape'),
  ('tshwane-university-of-technology', 'Arcadia Campus', 'Pretoria', 'Gauteng'),
  ('tshwane-university-of-technology', 'Arts Campus', 'Pretoria', 'Gauteng'),
  ('tshwane-university-of-technology', 'Ga-Rankuwa Campus', 'Pretoria', 'Gauteng'),
  ('tshwane-university-of-technology', 'Soshanguve North Campus', 'Pretoria', 'Gauteng'),
  ('tshwane-university-of-technology', 'Soshanguve South Campus', 'Pretoria', 'Gauteng'),
  ('tshwane-university-of-technology', 'eMalahleni Campus', 'eMalahleni', 'Mpumalanga'),
  ('tshwane-university-of-technology', 'Mbombela Campus', 'Mbombela', 'Mpumalanga'),
  ('tshwane-university-of-technology', 'Polokwane Campus', 'Polokwane', 'Limpopo'),
  ('university-of-cape-town', 'Upper Campus', 'Cape Town', 'Western Cape'),
  ('university-of-cape-town', 'Middle Campus', 'Cape Town', 'Western Cape'),
  ('university-of-cape-town', 'Lower Campus', 'Cape Town', 'Western Cape'),
  ('university-of-cape-town', 'Hiddingh Campus', 'Cape Town', 'Western Cape'),
  ('university-of-cape-town', 'Medical Campus', 'Cape Town', 'Western Cape'),
  ('university-of-fort-hare', 'Alice Campus', 'Alice', 'Eastern Cape'),
  ('university-of-fort-hare', 'East London Campus', 'East London', 'Eastern Cape'),
  ('university-of-fort-hare', 'Bhisho Campus', 'Bhisho', 'Eastern Cape'),
  ('university-of-johannesburg', 'Auckland Park Kingsway Campus', 'Johannesburg', 'Gauteng'),
  ('university-of-johannesburg', 'Auckland Park Bunting Road Campus', 'Johannesburg', 'Gauteng'),
  ('university-of-johannesburg', 'Doornfontein Campus', 'Johannesburg', 'Gauteng'),
  ('university-of-johannesburg', 'Soweto Campus', 'Johannesburg', 'Gauteng'),
  ('university-of-kwazulu-natal', 'Howard College Campus', 'Durban', 'KwaZulu-Natal'),
  ('university-of-kwazulu-natal', 'Edgewood Campus', 'Pinetown', 'KwaZulu-Natal'),
  ('university-of-kwazulu-natal', 'Medical School Campus', 'Durban', 'KwaZulu-Natal'),
  ('university-of-kwazulu-natal', 'Westville Campus', 'Durban', 'KwaZulu-Natal'),
  ('university-of-kwazulu-natal', 'Pietermaritzburg Campus', 'Pietermaritzburg', 'KwaZulu-Natal'),
  ('university-of-limpopo', 'Turfloop Campus', 'Mankweng', 'Limpopo'),
  ('university-of-mpumalanga', 'Mbombela Campus', 'Mbombela', 'Mpumalanga'),
  ('university-of-mpumalanga', 'Siyabuswa Campus', 'Siyabuswa', 'Mpumalanga'),
  ('university-of-pretoria', 'Hatfield Campus', 'Pretoria', 'Gauteng'),
  ('university-of-pretoria', 'Groenkloof Campus', 'Pretoria', 'Gauteng'),
  ('university-of-pretoria', 'Prinshof Campus', 'Pretoria', 'Gauteng'),
  ('university-of-pretoria', 'Onderstepoort Campus', 'Pretoria', 'Gauteng'),
  ('university-of-pretoria', 'Mamelodi Campus', 'Pretoria', 'Gauteng'),
  ('university-of-south-africa', 'Muckleneuk Campus', 'Pretoria', 'Gauteng'),
  ('university-of-south-africa', 'Regional Service Centres', 'Nationwide', 'South Africa'),
  ('university-of-the-free-state', 'Bloemfontein Campus', 'Bloemfontein', 'Free State'),
  ('university-of-the-free-state', 'Qwaqwa Campus', 'Phuthaditjhaba', 'Free State'),
  ('university-of-the-free-state', 'South Campus', 'Bloemfontein', 'Free State'),
  ('university-of-the-western-cape', 'Main Campus', 'Bellville', 'Western Cape'),
  ('university-of-the-western-cape', 'Bellville Park Campus', 'Bellville', 'Western Cape'),
  ('university-of-the-witwatersrand', 'East Campus', 'Johannesburg', 'Gauteng'),
  ('university-of-the-witwatersrand', 'West Campus', 'Johannesburg', 'Gauteng'),
  ('university-of-the-witwatersrand', 'Education Campus', 'Johannesburg', 'Gauteng'),
  ('university-of-the-witwatersrand', 'Medical School', 'Johannesburg', 'Gauteng'),
  ('university-of-venda', 'Main Campus', 'Thohoyandou', 'Limpopo'),
  ('university-of-zululand', 'KwaDlangezwa Campus', 'Empangeni', 'KwaZulu-Natal'),
  ('university-of-zululand', 'Richards Bay Campus', 'Richards Bay', 'KwaZulu-Natal'),
  ('walter-sisulu-university', 'Mthatha Campus', 'Mthatha', 'Eastern Cape'),
  ('walter-sisulu-university', 'Buffalo City Campus', 'East London', 'Eastern Cape'),
  ('walter-sisulu-university', 'Butterworth Campus', 'Butterworth', 'Eastern Cape'),
  ('walter-sisulu-university', 'Komani Campus', 'Komani', 'Eastern Cape')
) as campus_seed(university_slug, name, city, province)
join public.universities
  on universities.slug = campus_seed.university_slug
on conflict (university_id, name) do update
set
  city = excluded.city,
  province = excluded.province;


